import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export type ReportKind =
  | "monthly"
  | "goals"
  | "ai_insights"
  | "spending"
  | "elite_forecast";

export interface ReportInput {
  kind: ReportKind;
  userName: string;
  currency: string;
  monthlyIncome: number;
  transactions: Array<{
    id: string;
    title: string;
    amount: number;
    type: string;
    category: string | null;
    transaction_date: string;
  }>;
  goals: Array<{
    goal_name: string;
    target_amount: number;
    current_amount: number;
    deadline: string | null;
    category: string | null;
  }>;
  stats: { income: number; expenses: number; balance: number; savings: number; savingsRate: number };
  categoryData: Array<{ name: string; value: number }>;
  trendData: Array<{ name: string; income: number; expense: number }>;
  tier: "free" | "pro" | "elite";
}

const fmt = (n: number, c = "INR") =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: c, maximumFractionDigits: 0 }).format(n || 0);

const COLORS = {
  primary: [79, 70, 229] as [number, number, number], // indigo-600
  accent: [139, 92, 246] as [number, number, number], // violet-500
  ink: [17, 24, 39] as [number, number, number],
  muted: [107, 114, 128] as [number, number, number],
  line: [229, 231, 235] as [number, number, number],
  surface: [249, 250, 251] as [number, number, number],
  good: [16, 185, 129] as [number, number, number],
  bad: [239, 68, 68] as [number, number, number],
};

const CAT_HEX: Record<string, [number, number, number]> = {
  Food: [245, 158, 11], Shopping: [236, 72, 153], Travel: [59, 130, 246],
  Bills: [139, 92, 246], Entertainment: [6, 182, 212], Health: [16, 185, 129],
  Education: [99, 102, 241], Salary: [34, 197, 94], Investment: [14, 165, 233],
  Other: [148, 163, 184],
};

function header(doc: jsPDF, title: string, subtitle: string, tier: string) {
  const W = doc.internal.pageSize.getWidth();
  // gradient header strip (faked with 3 bands)
  const grads: [number, number, number][] = [[99, 102, 241], [139, 92, 246], [217, 70, 239]];
  const stripH = 44;
  for (let i = 0; i < 60; i++) {
    const t = i / 60;
    const [r1, g1, b1] = grads[0], [r2, g2, b2] = grads[1], [r3, g3, b3] = grads[2];
    const r = t < 0.5 ? r1 + (r2 - r1) * (t * 2) : r2 + (r3 - r2) * ((t - 0.5) * 2);
    const g = t < 0.5 ? g1 + (g2 - g1) * (t * 2) : g2 + (g3 - g2) * ((t - 0.5) * 2);
    const b = t < 0.5 ? b1 + (b2 - b1) * (t * 2) : b2 + (b3 - b2) * ((t - 0.5) * 2);
    doc.setFillColor(r, g, b);
    doc.rect((W / 60) * i, 0, W / 60 + 0.5, stripH, "F");
  }
  // logo block
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(20, 12, 22, 22, 5, 5, "F");
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(13); doc.setFont("helvetica", "bold");
  doc.text("FT", 31, 26, { align: "center" });

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15); doc.setFont("helvetica", "bold");
  doc.text("FinTrack AI", 50, 22);
  doc.setFontSize(9); doc.setFont("helvetica", "normal");
  doc.text("Intelligent Financial Operating System", 50, 30);

  // tier pill
  doc.setFillColor(255, 255, 255);
  const pill = tier === "elite" ? "ELITE AI+" : tier === "pro" ? "PRO AI" : "STARTER";
  const pw = doc.getTextWidth(pill) + 14;
  doc.roundedRect(W - pw - 20, 14, pw, 16, 8, 8, "F");
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(8); doc.setFont("helvetica", "bold");
  doc.text(pill, W - pw / 2 - 20, 24, { align: "center" });

  // title block
  doc.setTextColor(...COLORS.ink);
  doc.setFontSize(22); doc.setFont("helvetica", "bold");
  doc.text(title, 20, stripH + 22);
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.muted);
  doc.text(subtitle, 20, stripH + 30);
}

function footer(doc: jsPDF) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setDrawColor(...COLORS.line);
    doc.line(20, H - 18, W - 20, H - 18);
    doc.setFontSize(8); doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.muted);
    doc.text("Generated by FinTrack AI · Confidential", 20, H - 10);
    doc.text(`Page ${i} of ${total}`, W - 20, H - 10, { align: "right" });
  }
}

function sectionTitle(doc: jsPDF, label: string, y: number) {
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.8);
  doc.line(20, y - 4, 26, y - 4);
  doc.setFontSize(13); doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.ink);
  doc.text(label, 30, y);
  return y + 8;
}

function statCards(
  doc: jsPDF,
  y: number,
  items: Array<{ label: string; value: string; tone?: "good" | "bad" | "neutral" }>,
) {
  const W = doc.internal.pageSize.getWidth();
  const gap = 6;
  const cardW = (W - 40 - gap * (items.length - 1)) / items.length;
  items.forEach((it, i) => {
    const x = 20 + i * (cardW + gap);
    doc.setFillColor(...COLORS.surface);
    doc.roundedRect(x, y, cardW, 28, 4, 4, "F");
    doc.setFontSize(7); doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.muted);
    doc.text(it.label.toUpperCase(), x + 6, y + 8);
    doc.setFontSize(13); doc.setFont("helvetica", "bold");
    const tone = it.tone === "good" ? COLORS.good : it.tone === "bad" ? COLORS.bad : COLORS.ink;
    doc.setTextColor(...tone);
    doc.text(it.value, x + 6, y + 20);
  });
  return y + 36;
}

function categoryBars(doc: jsPDF, y: number, data: { name: string; value: number }[], currency: string) {
  const W = doc.internal.pageSize.getWidth();
  const total = data.reduce((s, d) => s + d.value, 0) || 1;
  const items = [...data].sort((a, b) => b.value - a.value).slice(0, 8);
  items.forEach((it) => {
    const pct = it.value / total;
    doc.setFontSize(9); doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.ink);
    doc.text(it.name, 20, y);
    doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.muted);
    doc.text(`${fmt(it.value, currency)} · ${Math.round(pct * 100)}%`, W - 20, y, { align: "right" });
    y += 2;
    doc.setFillColor(...COLORS.line);
    doc.roundedRect(20, y, W - 40, 4, 2, 2, "F");
    const c = CAT_HEX[it.name] || COLORS.accent;
    doc.setFillColor(...c);
    doc.roundedRect(20, y, (W - 40) * pct, 4, 2, 2, "F");
    y += 10;
  });
  return y;
}

function trendChart(doc: jsPDF, y: number, data: { name: string; income: number; expense: number }[]) {
  const W = doc.internal.pageSize.getWidth();
  const chartW = W - 40;
  const chartH = 50;
  // background
  doc.setFillColor(...COLORS.surface);
  doc.roundedRect(20, y, chartW, chartH, 4, 4, "F");
  const max = Math.max(1, ...data.flatMap((d) => [d.income, d.expense]));
  const barW = (chartW - 20) / (data.length * 2 + data.length - 1);
  let x = 30;
  data.forEach((d) => {
    const incH = (d.income / max) * (chartH - 18);
    const expH = (d.expense / max) * (chartH - 18);
    doc.setFillColor(...COLORS.good);
    doc.roundedRect(x, y + chartH - 12 - incH, barW, Math.max(0.5, incH), 1, 1, "F");
    doc.setFillColor(...COLORS.bad);
    doc.roundedRect(x + barW + 1, y + chartH - 12 - expH, barW, Math.max(0.5, expH), 1, 1, "F");
    doc.setFontSize(7); doc.setTextColor(...COLORS.muted);
    doc.text(d.name, x + barW, y + chartH - 4, { align: "center" });
    x += barW * 2 + 5;
  });
  // legend
  doc.setFillColor(...COLORS.good); doc.circle(W - 70, y + 6, 1.5, "F");
  doc.setFontSize(7); doc.setTextColor(...COLORS.muted); doc.text("Income", W - 65, y + 7);
  doc.setFillColor(...COLORS.bad); doc.circle(W - 45, y + 6, 1.5, "F");
  doc.text("Expense", W - 40, y + 7);
  return y + chartH + 8;
}

function healthScore(stats: ReportInput["stats"], goalsCount: number) {
  let score = 50;
  if (stats.savingsRate >= 30) score += 25;
  else if (stats.savingsRate >= 15) score += 15;
  else if (stats.savingsRate > 0) score += 5;
  else score -= 15;
  if (stats.balance > 0) score += 10;
  if (goalsCount > 0) score += 10;
  if (stats.expenses > stats.income && stats.income > 0) score -= 20;
  return Math.max(0, Math.min(100, score));
}

function aiRecommendations(input: ReportInput): string[] {
  const r: string[] = [];
  const { stats, categoryData, goals, tier } = input;
  if (stats.savingsRate < 20) r.push(`Your savings rate is ${stats.savingsRate}%. Aim for at least 20% by trimming discretionary categories.`);
  else r.push(`Excellent — a ${stats.savingsRate}% savings rate puts you ahead of 70% of peers.`);
  const top = [...categoryData].sort((a, b) => b.value - a.value)[0];
  if (top) r.push(`${top.name} is your largest category. Consider setting a monthly cap to free up liquidity.`);
  if (goals.length === 0) r.push("No goals defined. Set an emergency fund target (3–6 months of expenses) as a starting point.");
  else {
    const behind = goals.find((g) => g.deadline && Number(g.current_amount) / Math.max(1, Number(g.target_amount)) < 0.4);
    if (behind) r.push(`Goal "${behind.goal_name}" is tracking under 40%. Increase monthly contribution to stay on schedule.`);
  }
  if (tier === "elite") r.push("Elite forecast: based on current trajectory, you can reach 6-month emergency reserve in ~9 months with a 5% contribution uplift.");
  return r;
}

export async function exportReport(input: ReportInput): Promise<void> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const titles: Record<ReportKind, [string, string]> = {
    monthly: ["Monthly Financial Report", "A complete snapshot of your finances this month."],
    goals: ["Goal Progress Report", "Track every milestone toward your financial goals."],
    ai_insights: ["AI Insights Report", "Lumo AI’s personalized recommendations & observations."],
    spending: ["Spending Analytics Report", "Where every rupee, dollar and euro is going."],
    elite_forecast: ["Elite Wealth Forecast", "Multi-horizon projections & private intelligence."],
  };
  const [title, subtitle] = titles[input.kind];
  header(doc, title, `${subtitle}  ·  Prepared for ${input.userName}  ·  ${new Date().toLocaleDateString("en", { year: "numeric", month: "long", day: "numeric" })}`, input.tier);

  let y = 90;
  // hero stat cards — always
  y = statCards(doc, y, [
    { label: "Income", value: fmt(input.stats.income, input.currency), tone: "good" },
    { label: "Expenses", value: fmt(input.stats.expenses, input.currency), tone: "bad" },
    { label: "Net", value: fmt(input.stats.balance, input.currency), tone: input.stats.balance >= 0 ? "good" : "bad" },
    { label: "Savings Rate", value: `${input.stats.savingsRate}%` },
  ]);

  if (input.kind === "monthly" || input.kind === "spending" || input.kind === "elite_forecast") {
    y = sectionTitle(doc, "Income vs Expense — Last 7 Days", y + 4);
    y = trendChart(doc, y, input.trendData);
  }

  if (input.kind === "monthly" || input.kind === "spending") {
    y = sectionTitle(doc, "Category Breakdown", y + 4);
    y = categoryBars(doc, y + 2, input.categoryData, input.currency);
  }

  // Health score
  if (input.kind === "monthly" || input.kind === "ai_insights" || input.kind === "elite_forecast") {
    if (y > 680) { doc.addPage(); y = 40; }
    y = sectionTitle(doc, "Financial Health Score", y + 6);
    const score = healthScore(input.stats, input.goals.length);
    const W = doc.internal.pageSize.getWidth();
    doc.setFillColor(...COLORS.surface);
    doc.roundedRect(20, y, W - 40, 36, 4, 4, "F");
    doc.setFontSize(28); doc.setFont("helvetica", "bold");
    doc.setTextColor(...(score >= 70 ? COLORS.good : score >= 40 ? COLORS.primary : COLORS.bad));
    doc.text(`${score}`, 36, y + 25);
    doc.setFontSize(8); doc.setTextColor(...COLORS.muted); doc.text("/100", 70, y + 25);
    // bar
    doc.setFillColor(...COLORS.line); doc.roundedRect(90, y + 18, W - 130, 6, 3, 3, "F");
    doc.setFillColor(...COLORS.primary); doc.roundedRect(90, y + 18, ((W - 130) * score) / 100, 6, 3, 3, "F");
    doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.ink);
    doc.text(score >= 70 ? "Strong — keep this momentum." : score >= 40 ? "Stable — room to optimize." : "Needs attention — see recommendations.", 90, y + 14);
    y += 44;
  }

  // Goals
  if (input.kind === "goals" || input.kind === "monthly" || input.kind === "elite_forecast") {
    if (y > 680) { doc.addPage(); y = 40; }
    y = sectionTitle(doc, "Goals Progress", y + 4);
    if (input.goals.length === 0) {
      doc.setFontSize(9); doc.setTextColor(...COLORS.muted);
      doc.text("No goals defined yet.", 20, y); y += 10;
    } else {
      autoTable(doc, {
        startY: y,
        head: [["Goal", "Category", "Saved", "Target", "Progress", "Deadline"]],
        body: input.goals.map((g) => {
          const pct = Math.min(100, Math.round((Number(g.current_amount) / Math.max(1, Number(g.target_amount))) * 100));
          return [
            g.goal_name,
            g.category || "—",
            fmt(Number(g.current_amount), input.currency),
            fmt(Number(g.target_amount), input.currency),
            `${pct}%`,
            g.deadline || "—",
          ];
        }),
        styles: { fontSize: 9, cellPadding: 6 },
        headStyles: { fillColor: COLORS.primary, textColor: 255, fontStyle: "bold" },
        alternateRowStyles: { fillColor: COLORS.surface },
        margin: { left: 20, right: 20 },
      });
      // @ts-expect-error autotable types
      y = doc.lastAutoTable.finalY + 10;
    }
  }

  // AI Recommendations
  if (input.kind === "ai_insights" || input.kind === "monthly" || input.kind === "elite_forecast") {
    if (y > 680) { doc.addPage(); y = 40; }
    y = sectionTitle(doc, "AI Recommendations", y + 4);
    aiRecommendations(input).forEach((rec) => {
      if (y > 760) { doc.addPage(); y = 40; }
      doc.setFillColor(245, 243, 255);
      doc.roundedRect(20, y - 6, doc.internal.pageSize.getWidth() - 40, 18 + Math.floor(rec.length / 90) * 9, 4, 4, "F");
      doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.ink);
      const lines = doc.splitTextToSize(`• ${rec}`, doc.internal.pageSize.getWidth() - 56);
      doc.text(lines, 28, y + 2);
      y += lines.length * 11 + 6;
    });
  }

  // Elite forecast extras
  if (input.kind === "elite_forecast") {
    if (y > 660) { doc.addPage(); y = 40; }
    y = sectionTitle(doc, "12-Month Wealth Trajectory (projected)", y + 4);
    const monthlySaving = Math.max(0, input.stats.savings);
    const W = doc.internal.pageSize.getWidth();
    autoTable(doc, {
      startY: y,
      head: [["Horizon", "Conservative", "Base", "Optimistic"]],
      body: [3, 6, 9, 12].map((m) => [
        `${m} months`,
        fmt(monthlySaving * m * 0.85, input.currency),
        fmt(monthlySaving * m, input.currency),
        fmt(monthlySaving * m * 1.18, input.currency),
      ]),
      styles: { fontSize: 9, cellPadding: 7 },
      headStyles: { fillColor: COLORS.accent, textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: COLORS.surface },
      margin: { left: 20, right: 20 },
    });
    // @ts-expect-error autotable types
    y = doc.lastAutoTable.finalY + 10;
  }

  // Transactions table — for monthly, spending
  if (input.kind === "monthly" || input.kind === "spending") {
    if (y > 660) { doc.addPage(); y = 40; }
    y = sectionTitle(doc, "Recent Transactions", y + 4);
    const recent = input.transactions.slice(0, 25);
    autoTable(doc, {
      startY: y,
      head: [["Date", "Title", "Category", "Type", "Amount"]],
      body: recent.map((t) => [
        t.transaction_date,
        t.title,
        t.category || "—",
        t.type,
        `${t.type === "expense" ? "-" : "+"}${fmt(Number(t.amount), input.currency)}`,
      ]),
      styles: { fontSize: 9, cellPadding: 6 },
      headStyles: { fillColor: COLORS.ink, textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: COLORS.surface },
      margin: { left: 20, right: 20 },
      columnStyles: { 4: { halign: "right" } },
    });
  }

  footer(doc);
  const filename = `FinTrack-${input.kind}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
