project_id = "fncmsgnjebbmdxjpreir"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.ai-router]
verify_jwt = false
