import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Download, Sparkles, TrendingUp, Target, Brain, Crown, Loader2, Check } from "lucide-react";
import { exportReport, type ReportKind, type ReportInput } from "@/lib/pdfExport";
import { toast } from "sonner";

interface Props {
  baseInput: Omit<ReportInput, "kind">;
  onUpgrade: () => void;
}

const REPORTS: { kind: ReportKind; title: string; subtitle: string; icon: typeof FileText; tone: string; tierGate?: "pro" | "elite" }[] = [
  { kind: "monthly", title: "Monthly Financial Report", subtitle: "Income, expenses, categories & transactions.", icon: FileText, tone: "from-indigo-500 to-blue-500" },
  { kind: "goals", title: "Goal Progress Report", subtitle: "Every milestone toward your goals.", icon: Target, tone: "from-emerald-500 to-teal-500" },
  { kind: "ai_insights", title: "AI Insights Report", subtitle: "Lumo’s personalized recommendations.", icon: Brain, tone: "from-violet-500 to-fuchsia-500", tierGate: "pro" },
  { kind: "spending", title: "Spending Analytics Report", subtitle: "Where every unit of currency goes.", icon: TrendingUp, tone: "from-amber-500 to-rose-500", tierGate: "pro" },
  { kind: "elite_forecast", title: "Elite Wealth Forecast", subtitle: "12-month multi-horizon projections.", icon: Crown, tone: "from-fuchsia-500 via-violet-500 to-indigo-500", tierGate: "elite" },
];

export const ExportCenter = ({ baseInput, onUpgrade }: Props) => {
  const [busy, setBusy] = useState<ReportKind | null>(null);
  const [done, setDone] = useState<ReportKind | null>(null);
  const tier = baseInput.tier;

  const run = async (kind: ReportKind, gate?: "pro" | "elite") => {
    if (gate === "pro" && tier === "free") { onUpgrade(); return; }
    if (gate === "elite" && tier !== "elite") { onUpgrade(); return; }
    try {
      setBusy(kind); setDone(null);
      await new Promise((r) => setTimeout(r, 600)); // cinematic delay
      await exportReport({ ...baseInput, kind });
      setDone(kind);
      toast.success("Report exported");
      setTimeout(() => setDone(null), 1800);
    } catch (e) {
      toast.error((e as Error).message || "Export failed");
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-display text-xl font-bold text-gray-900">Premium Exports</h2>
          <p className="text-sm text-gray-500">Investor-grade PDFs generated by Lumo AI.</p>
        </div>
        <div className="hidden sm:flex items-center gap-1.5 text-xs font-semibold text-violet-600 bg-violet-50 px-3 py-1.5 rounded-full">
          <Sparkles className="w-3.5 h-3.5" /> PDF Engine v2
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {REPORTS.map((r) => {
          const locked = (r.tierGate === "pro" && tier === "free") || (r.tierGate === "elite" && tier !== "elite");
          const isBusy = busy === r.kind;
          const isDone = done === r.kind;
          const Icon = r.icon;
          return (
            <motion.button
              key={r.kind}
              whileHover={{ y: -3 }}
              onClick={() => run(r.kind, r.tierGate)}
              disabled={isBusy}
              className="relative text-left rounded-3xl p-5 bg-white border border-gray-100 shadow-sm hover:shadow-xl transition overflow-hidden group"
            >
              <div className={`absolute -top-12 -right-12 w-40 h-40 rounded-full bg-gradient-to-br ${r.tone} opacity-10 blur-2xl group-hover:opacity-20 transition`} />
              <div className="flex items-start justify-between relative">
                <div className={`w-11 h-11 rounded-2xl bg-gradient-to-br ${r.tone} flex items-center justify-center text-white shadow-lg`}>
                  <Icon className="w-5 h-5" />
                </div>
                {locked ? (
                  <span className="text-[10px] font-bold px-2 py-1 rounded-full bg-violet-50 text-violet-700 border border-violet-100 flex items-center gap-1">
                    <Crown className="w-3 h-3" /> {r.tierGate === "elite" ? "ELITE" : "PRO"}
                  </span>
                ) : (
                  <AnimatePresence mode="wait">
                    {isDone ? (
                      <motion.span key="done" initial={{ scale: 0 }} animate={{ scale: 1 }} exit={{ scale: 0 }} className="text-emerald-600 bg-emerald-50 rounded-full p-1.5"><Check className="w-3.5 h-3.5" /></motion.span>
                    ) : isBusy ? (
                      <motion.span key="busy" className="text-violet-600"><Loader2 className="w-4 h-4 animate-spin" /></motion.span>
                    ) : (
                      <motion.span key="dl" className="text-gray-400 group-hover:text-gray-900 transition"><Download className="w-4 h-4" /></motion.span>
                    )}
                  </AnimatePresence>
                )}
              </div>
              <h3 className="font-display text-base font-bold text-gray-900 mt-4">{r.title}</h3>
              <p className="text-xs text-gray-500 mt-1">{r.subtitle}</p>
              {isBusy && (
                <motion.div initial={{ width: 0 }} animate={{ width: "100%" }} transition={{ duration: 1.2 }} className={`absolute bottom-0 left-0 h-0.5 bg-gradient-to-r ${r.tone}`} />
              )}
            </motion.button>
          );
        })}
      </div>
    </div>
  );
};
